version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - internal_test_net
        ports:
            - "80:80"
        depends_on:
            - php
        environment:
            - VIRTUAL_PORT=80
            - VIRTUAL_HOST=project.local
        container_name: practic_nginx

    php:
        build:
            context: .
            dockerfile: _docker/php/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./_docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - internal_test_net
        depends_on:
            - db
        container_name: practic_php

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        command:
          [
              'mysqld',
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci'
          ]
        container_name: practic_db

networks:
    internal_test_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.1/28
